### ISSUE TITLE
Error in console after selecting the site in the grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-wireframe#5]
1. Open Applications  and install `Wireframe`
2. Go to Content Studio and select the imported site

BUG: 
errors in console appear  after selecting the site

![image](https://user-images.githubusercontent.com/3728712/57683808-25286e00-763d-11e9-87ea-1ea5737129c6.png)

**Comment by alansemenov** [comment]
Fixed and released v1.1.1
